import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Aside from '@/components/aside';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Gestion d'achats",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className + ' bg-gray-50' }>
        <main className='w-screen h-screen flex overflow-hidden'>
        {children}
        </main>
      </body>
    </html>
  );
}
